version: '3.1'
services:
    enveloper:
        volumes:
            - .:/app
        environment:
            - SYMFONY_ENV=test
            - ENVELOPER_DB_DSN=sqlite:////app/tests/data/enveloper_test.sqlite
            - ENVELOPER_PIPEPRINT_URL=http://pipeprint
