app:
    resource: '@AppBundle/Controller/'
    type: annotation

error_404:
  path: /{req}
  defaults: { _controller: 'AppBundle\Controller\ErrorController::pageNotFoundAction' }
  requirements:
      req: ".+"