Outstack\Enveloper\Mail\SentMessage:
    type: entity
    id:
        id:
            type: guid
            generator: { strategy: UUID }
    fields:
        template:
            type: string
            length: 200
        parameters:
            type: json_array
        sentAt:
            type: datetime_immutable
            nullable: true
        resolvedMessage:
            type: object