Outstack\Enveloper\Mail\OutboxItem:
    type: entity
    table: sent_message
    id:
        id:
            type: guid
            generator: { strategy: UUID }
    fields:
        template:
            type: string
            length: 200
        parameters:
            type: json_array
        resolvedMessage:
            type: object