openapi: 3.0.0
info:
  description: |

    # Introduction
    Enveloper is a small service intended to be run in your infrastucture to speed up developing and testing
    transactional emails in your application.

    This document describes the API, its endpoints and their structure. For information on getting started,
    take a look at the [project on github](https://github.com/outstack/enveloper) or the
    [getting started guide](https://github.com/outstack/enveloper/blob/master/docs/01-getting-started.md).

    # Authentication
    There is currently no authentication mechanism for Enveloper. You should either avoid exposing it publicly over
    the internet or place it behind an API gateway such as Tyk, Kong or Amazon API Gateway.

  version: 1.0.0
  title: Enveloper API
  contact:
    email: adamquaile@gmail.com
  license:
    name: No Licence
    url: 'https://github.com/outstack/enveloper/blob/master/LICENSE.md'
externalDocs:
  description: View the Enveloper Github repository
  url: 'https://github.com/outstack/enveloper'
tags:
  - name: Outbox
    description: List and send messages
paths:
  /outbox/preview:
    post:
      tags:
        - Outbox
      summary: Preview a templated message, without sending
      requestBody:
        content:
          application/json:
            schema:
              $ref: './build/endpoints/outbox/preview/post.requestBody.schema.openapi'
      responses:
        '200':
          description: 'Preview successfully rendered'
          content:
            text/plain:
              schema:
                type: string
              example: |
                Your order has shipped
                ----------------------

                Thanks for your order - it's on its way!
            text/html:
              schema:
                type: string
              example: |
                <h1>Your order has shipped</h1>
                <p>Thanks for your order - it's on its way!</p>
        '406':
          description: Not acceptable
          content:
            a
  /outbox:
    post:
      tags:
        - Outbox
      summary: Send a templated message
      requestBody:
        content:
          application/json:
            schema:
              $ref: './build/endpoints/outbox/post.requestBody.schema.openapi'
      responses:
        '204':
          description: 'Message Sent'
    get:
      summary: Lists recently sent messages
      tags:
        - Outbox
      responses:
        '200':
          description: 'List loaded successfully'
          content:
            application/json:
              schema:
                $ref: './build/endpoints/outbox/get.responseBody.schema.openapi'
  /outbox/{id}:
    get:
      operationId: getSentMessageById
      summary: Finds sent message by ID
      tags:
        - Outbox
      responses:
        '200':
          description: 'Message Found'
          content:
            application/json:
              schema:
                $ref: './build/endpoints/outbox/getSentMessageById.responseBody.schema.openapi'
        '404':
          description: 'No such message'
servers:
  - url: 'https://enveloper.example.com'
components:
  schemas: {}
